#cloud-config
hostname: rancher
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTIISGZxb+d8sm2KaUfMUjJ2cDjDNjTBg/kl0dvypqVOsbJfAabbl9FULPlcBAOYCILmozvHZKKMhab9iIdIXF/FNtATfxzzWErk97mvqp7eY7lm5PJdcJ3hRXrX5KLQFEq90vBvZOEfXaiCm6OGyMKGKx/gicmle6W6/bcpegTgfvD2TtNVEI5++x9IRhlyAPGRZ4F1UmMnUsAiUlQx4CdbYwQ6lrxavwh5JeI0110CYs1zisPCoWz5/ZfRG8mzZKl7gRHoRE9zjy5N5+elDi0jcjWqkyCWeaVgTg+juLCoWXHiURHqLYF7x3w3aLZb3K8GtdS5etCTvGf4DpogIZ ronny@MacBook-Pro-van-Ronny.local

rancher:
  docker:
    tls: false
  console: debian
  resize_device: /dev/sda
  defaults:
    system_docker_logs: /usr/share/ros/oem/system-docker.log
  network:
    eth0:
      mtu: 1500
      dhcp: true
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
  sysctl:
    net.ipv4.conf.default.rp_filter: 1
  disable:
  - autologin
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    - /dev/vda
